#enable GPIO peripheral
CONFIG_GPIO=y

# enable timer
CONFIG_NRFX_TIMER=y
CONFIG_RTC=y
CONFIG_SYS_CLOCK_EXISTS=y
CONFIG_NRF_RTC_TIMER=y
CONFIG_COUNTER=y

#enable I2C
CONFIG_SPI=y
CONFIG_SENSOR=y
CONFIG_BMI160=y
CONFIG_BMI160_ACCEL_ODR_50=y
CONFIG_BMI160_ACCEL_RANGE_4G=y
CONFIG_BMI160_ACCEL_PMU_LOW_POWER=y
CONFIG_BMI160_TRIGGER_GLOBAL_THREAD=y
CONFIG_BMI160_GYRO_PMU_SUSPEND=y

CONFIG_BT_RX_STACK_SIZE=2048

# enable UART/CONSOLE
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=1

# enable BT
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="CSC Sensor"
CONFIG_BT_DEVICE_APPEARANCE=1157
CONFIG_BT_MAX_CONN=2

# BLE FOTA
CONFIG_NCS_SAMPLE_MCUMGR_BT_OTA_DFU=y
CONFIG_MCUMGR_TRANSPORT_BT_PERM_RW_AUTHEN=y
